name: Make OrangeFox Recovery v2

on:
  workflow_dispatch:
    inputs:
      LIBRARY_NAME:
        description: 'LIBRARY_NAME'
        required: true
        default: 'twrp'
      Ver_OFRP_URL:
        description: 'Ver_OFRP_URL'
        required: true
        default: 'fox_12.1'
      Ver_OFRP2_URL:
        description: 'Ver_OFRP2_URL'
        required: true
        default: '12.1'
      DEVICE_URL:
        description: 'DEVICE_URL'
        required: true
        default: 'https://github.com/brigudav/android_device_xiaomi_surya_twrp.git'
      DEVICE_BRANCH:
        description: 'DEVICE_BRANCH'
        required: true
        default: 'android-12.1'
      DEVICE_PATH:
        description: 'DEVICE_PATH'
        required: true
        default: 'device/xiaomi/surya'
      DEVICE_NAME:
        description: 'DEVICE_NAME'
        required: true
        default: 'surya'
      DEVICE_TYPE:
        description: 'DEVICE_TYPE'
        required: true
        default: 'recovery'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-18.04

    steps:
    - name: Remove Useless Package
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d
        sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo apt -y autoremove --purge
        sudo apt -y autoclean
        sudo apt clean

    - name: Check Out
      uses: actions/checkout@v3

    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10

    - name: Prepare the environment
      run: |
        git clone https://gitlab.com/OrangeFox/misc/scripts
        cd scripts
        sudo bash setup/android_build_env.sh
        sudo bash setup/install_android_sdk.sh || true

    - name: Set variables
      run: |
        echo "::set-output name=date::$(date +%F)"
      id: var

    - name: How much space
      run: |
        df -h

    - name: Initialize OFRP
      run: |
        PATH=~/bin:$PATH
        mkdir workspace
        cd workspace
        echo "::set-output name=pwd::$(pwd)"
        git config --global user.name "brigudav"
        git config --global user.email "alexvl1972@hotmail.com"
        git clone https://gitlab.com/OrangeFox/sync.git
      id: pwd

    - name: Sync OFRP
      run: |
        PATH=~/bin:$PATH
        cd workspace/sync
        ./orangefox_sync.sh --branch ${{ github.event.inputs.Ver_OFRP2_URL }} --path ~/${{ github.event.inputs.Ver_OFRP_URL }}

    - name: Clone device
      run: |
        PATH=~/bin:$PATH
        cd /home/runner/${{ github.event.inputs.Ver_OFRP_URL }}
        git clone ${{ github.event.inputs.DEVICE_URL }} -b ${{ github.event.inputs.DEVICE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}

    - name: How much space
      run: |
        df -h

    - name: Building
      run: |
        PATH=~/bin:$PATH
        cd /home/runner/${{ github.event.inputs.Ver_OFRP_URL }}
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
        export LC_ALL="C"
        lunch ${{ github.event.inputs.LIBRARY_NAME }}_${{ github.event.inputs.DEVICE_NAME }}-eng && mka adbd ${{ github.event.inputs.DEVICE_TYPE }}image

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          /home/runner/${{ github.event.inputs.Ver_OFRP_URL }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/*.zip
          /home/runner/${{ github.event.inputs.Ver_OFRP_URL }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/${{ github.event.inputs.DEVICE_TYPE }}.img
        name: ${{ github.event.inputs.DEVICE_NAME }}-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: Recovery for ${{ github.event.inputs.DEVICE_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.TEST }}
